spring:
  datasource:
    url: jdbc:mysql://192.168.1.119:3306/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.119
    port: 6379
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomact/
#  file: /var/log/tomact/sell.log
#  level:
#    cn.coldwarm7.sell.LoggerTest: debug

